apiVersion: apps/v1
kind: Deployment
metadata:
  name: balcha-healthcare-deploy
  labels:
    app: balcha-healthcare-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balcha-healthcare-deploy
  template:
    metadata:
      labels:
        app: balcha-healthcare-deploy
    spec:
      containers:
      - name: balcha-healthcare-container
        image: balcha/healthcare_domin:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: balcha-healthcare-np-service
  labels:
    app: balcha-healthcare-deploy
spec:
  selector:
    app: balcha-healthcare-deploy
  type: NodePort
  ports:
  - nodePort: 31400
    port: 8082
    targetPort: 8082
