apiVersion: apps/v1
kind: Deployment
metadata:
  name: balcha-deploy
  labels:
    app: healthcare_app
spec:
  replicas:3
  selector:
    matchLabels:
      app: healthcare_app
  template:
    metadata:
      labels:
        app: healthcare_app
    spec:
      containers:
      - name: health-care-container
        image: balcha/healthcare_domin:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: balcha-np-service
  labels:
    app: healthcare_app
spec:
  selector:
    app: healthcare_app
  type: NodePort
  ports:
  - nodePort: 30410
    port: 9090
    targetPort: 9090
